name: Run Go File

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-go-file:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    # Step 3: List files (Optional - Debugging)
    - name: List repository files
      run: ls -R

    # Step 4: Run the Go file
    - name: Run Go file
      run: go run ./golearn_1/basics/add.go

